nodeLinker: node-modules

# https://dev.to/arcanis/implicit-transitive-peer-dependencies-ed0
packageExtensions:
  'prettier-plugin-css-order@*':
    peerDependencies:
      'postcss': '^8.4.35'
  '@typescript-eslint/utils@*':
    peerDependenciesMeta:
      'typescript':
        optional: false

yarnPath: .yarn/releases/yarn-4.3.1.cjs
