nodeLinker: node-modules

# https://dev.to/arcanis/implicit-transitive-peer-dependencies-ed0
packageExtensions:
  '@typescript-eslint/utils@*':
    peerDependenciesMeta:
      'typescript':
        optional: false

yarnPath: .yarn/releases/yarn-4.3.1.cjs
